jexia/semaphore

.github/workflows/go.yml, README.md
=> GitHub workflow

specs/intermediate/intermediate.go, specs/intermediate/specs.go, specs/intermediate/tests/repeated.pass.hcl
Fixed hcl template to accept name on input. Previously the template label had to be defined inside repeated fields inside the input.
=> Fixed hcl template

specs/README.md
Removed any proto references in favor of the schema interfaces (#4 & #9).
=> Removed proto references

specs/lookup/lookup.go, specs/lookup/lookup_test.go, specs/strict/define.go, specs/strict/define_test.go, specs/strict/tests/basic.fail.hcl, specs/strict/tests/basic.fail.yaml, specs/strict/tests/basic.pass.hcl, specs/strict/tests/basic.pass.yaml, specs/strict/utils.go, specs/strict/utils_test.go
Strict type definitions check based of the specs structures.
=> Strict type definitions

specs/dependencies.go, specs/dependencies_test.go
Flow and call dependency resolving and circular dependency checks.
=> Dependency checks

specs/README.md, specs/intermediate/intermediate.go, specs/intermediate/specs.go, specs/intermediate/tests/services.pass.hcl, specs/specs.go, specs/strict/tests/basic.fail.hcl, specs/strict/tests/basic.pass.hcl
Updated specs to include service codec. A service codec defines the message format used to send to the given service.
=> Service codec

refs/refs.go, refs/refs_test.go
Data reference store used during runtime to store and fetch data.
=> Data reference store

specs/strict/tests/schema.pass.hcl
=> Fixed test schema

CONTRIBUTING.md, README.md, example/README.md, flow/README.md, specs/README.md
Updated README to include more examples and more detailed information.
=> updated README

protocol/headers.go, protocol/http/http.go, specs/lookup/lookup.go, specs/lookup/lookup_test.go, specs/strict/tests/header.pass.hcl, specs/template.go
Improved header references and bug fixes
=> Header references

README.md
A go report card badge is required to be available when applying to be included on the [awesome go list](https://github.com/avelino/awesome-go/blob/master/CONTRIBUTING.md#quality-standards).
=> GO report card badge

codec/json/object.go, codec/proto/message.go, flow/branches_test.go, flow/flow.go, flow/node.go, main.go, refs/refs.go, specs/intermediate/intermediate.go, specs/intermediate/specs_test.go, specs/lookup/lookup.go, specs/lookup/lookup_test.go, specs/strict/define.go, specs/strict/tests/header.fail.hcl, specs/strict/tests/header.fail.yaml, specs/template_test.go, utils/path.go
Fixes misspelled words as reported by [go report](https://goreportcard.com/report/github.com/jexia/maestro#misspell)
=> Fix misspelled words

specs/checks.go, specs/checks_test.go
This PR allows multiple endpoints to be defined for a single flow.
=> Multiple endpoints

specs/README.md
This PR fixes a small inconsistency inside the specs README.
=> specs README fix

examples/graphql/flow.hcl, flow.go, flow/flow.go, flow/flow_test.go, flow/node.go, flow/node_test.go, main.go, protocol/headers.go, protocol/http/README.md, protocol/http/caller.go, protocol/http/caller_test.go, protocol/http/http_test.go, protocol/http/listener_test.go, protocol/protocol.go, refs/call.go, specs/README.md, specs/lookup/lookup.go, specs/lookup/lookup_test.go, specs/specs.go, specs/strict/define.go, specs/strict/define_test.go
This PR allows callers to assign references that are configured through options.
=> Call references

codec/json/json_test.go, codec/proto/message_test.go, protocol/http/caller_test.go, protocol/http/http_test.go, refs/refs_test.go, specs/dependencies_test.go, specs/lookup/lookup_test.go, specs/trace/trace_test.go, specs/utils_test.go
Some files were not simplified with the simplify flag `gofmt -s`
=> gofmt simplify

README.md
I am in the process of setting up a Discord server. This PR includes the chat on discord badge for people to get access to the server.
=> Discord badge

codec/json/json_test.go, codec/json/object.go, codec/json/tests/complete.hcl, codec/json/tests/mock.hcl, codec/json/tests/schema.yaml, codec/json/types.go, codec/proto/builder.go, codec/proto/message.go, codec/proto/message_test.go, codec/proto/tests/complete.hcl, codec/proto/tests/complete.proto, codec/proto/tests/mock.hcl, codec/proto/tests/mock.proto, refs/refs.go
This PR includes support for repeated values.
```proto
message Query {
repeated string ids = 1;
}
```
=> Repeating values

cmd/maestro/config/arguments.go, cmd/maestro/main.go, cmd/maestro/middleware/hcl.go, cmd/maestro/run/run.go, cmd/maestro/validate/validate.go, internal/constructor/options.go, options.go, pkg/codec/proto/builder.go, pkg/codec/proto/descriptor.go, pkg/flow/flow.go, pkg/flow/flow_test.go, pkg/flow/node.go, pkg/flow/node_test.go, pkg/refs/refs.go, pkg/transport/graphql/arguments.go, pkg/transport/graphql/graphql.go, pkg/transport/graphql/object.go, pkg/transport/grpc/listener.go, pkg/transport/grpc/reflection.go, pkg/transport/http/listener.go, pkg/transport/protocol.go
This PR includes the possibility of fetching metrics (tracing and logging) from Maestro. This PR also includes bug fixes that need to be merged for the v2.0.0 release.
=> Initial metrics and bug fixes

pkg/constructor/constructor.go, pkg/definitions/hcl/hcl.go, pkg/definitions/hcl/hcl_test.go
Fixes a bug where includes were not included properly.
=> minor improvements and include bug fix

pkg/specs/property.go, pkg/specs/property_test.go, pkg/specs/referene.go
This PR refactors properties allowing for future types such as `OneOf`, `ManyOf`, and nested Arrays.
=> Refactor property

options.go, options_test.go, pkg/broker/broker.go, pkg/broker/logger/logger.go
This PR improves the test coverage of log levels inside the main package.
=> Improve test coverage options main package

pkg/transport/graphql/object.go, pkg/transport/graphql/response.go
This PR fixes the generation of GraphQL objects.
=> Graphql object generation

cmd/semaphore/daemon/client.go, cmd/semaphore/daemon/daemon.go, cmd/semaphore/generate/openapi3/openapi.go, cmd/semaphore/generate/protobuf/protobuf.go, cmd/semaphore/middleware/selector.go, cmd/semaphore/validate/validate.go, pkg/prettyerr/error.go, pkg/prettyerr/error_test.go, pkg/prettyerr/text_formatter.go, pkg/prettyerr/text_formatter_test.go
=> Implement pretty error in cli

pkg/prettyerr/text_formatter_test.go
=> refactored text-formatter-tests

cmd/semaphore/daemon/config/options.go
Also fix some other linter issues/refactoring in the file.
=> fix: OpenAPI3 config should not override the protobuf config
